"""empty message

Revision ID: 29afb6279f81
Revises: 8d7423ec3108
Create Date: 2025-02-22 20:52:55.984361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29afb6279f81'
down_revision = '8d7423ec3108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('national_id', sa.String(length=10), nullable=False),
    sa.Column('birthday', sa.String(length=10), nullable=False),
    sa.Column('university', sa.String(length=50), nullable=False),
    sa.Column('educational_stage', sa.String(length=20), nullable=False),
    sa.Column('academic_discipline', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('phone_number', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('national_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('register')
    # ### end Alembic commands ###
